kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: pivotaldata/centos-gcc-toolchain:6-slim
  commands:
    - add-apt-repository ppa:ubuntu-lxc/daily -y
    - apt-get update -qq
    - apt-get -y install -qq libfuse-dev libdbus-glib-1-dev libglib2.0-dev coreutils cgmanager
    - apt-get -y install -qq realpath || true
    - apt-get -y install -qq automake libtool libattr1-dev
    - ./bootstrap.sh
    - ./configure
    -  make -j4 && make tests
