kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: debian:7
  commands:
    - chmod a+x  add-apt-repository
    - cp add-apt-repository /usr/bin
    - add-apt-repository ppa:ubuntu-lxc/daily -y
    - apt-get update -qq
    - apt-get install -y gcc  make  realpath
    - apt-get -y install -qq libfuse-dev libdbus-glib-1-dev libglib2.0-dev coreutils
    - apt-get -y install -qq automake libtool libattr1-dev
    - ./bootstrap.sh
    - ./configure
    -  make -j4 && make tests
