kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: gcc:8
  commands:
      - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
      - sudo apt-get update -qq
      - sudo apt-get -y install -qq libfuse-dev libdbus-glib-1-dev libglib2.0-dev coreutils cgmanager
      - sudo apt-get -y install -qq realpath || true
      - sudo apt-get -y install -qq automake libtool libattr1-dev

     - ./bootstrap.sh
     - ./configure
     -  make -j4 && make tests
