kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: debian:7
  commands:
    - apt-get update
    - apt-get install -y gcc*  || true
    - apt-get install -y libcgmanager-dev || true
    - apt-get install -y libnih-dbus-dev || true
    - apt-get install -y libnih-dev || true
    - apt-get install -y libfuse-dev || true
    - ./bootstrap.sh
    - ./configure
    -  make -j4 && make tests
