kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: debian:7
  commands:
    - apt-get update
    - apt-get install -y gcc  make || true
    - apt-get install -y cgmanager* || true
    - apt-get install -y libnih* || true
    - apt-get install -y libfuse* || true
    - apt-get install -y libtool* || true
    - apt-get install -y automake || true
    - ./bootstrap.sh
    - ./configure
    -  make -j4 && make tests
