kind: pipeline
name: default

workspace:
   base: /c
   path: src/github.com/cuisongliu/lxcfs/

steps:
- name: build-fist
  image: debian:7
  commands:
    - apt-get update
    - apt-get install -y gcc  make 
    - apt-get install -y cgmanager* 
    - apt-get install -y libnih* 
    - apt-get install -y libfuse* 
    - apt-get install -y libtool* 
    - apt-get install -y automake 
    - ./bootstrap.sh
    - ./configure
    -  make -j4 && make tests
